# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sdbreport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSDBReport(object):
    def setupUi(self, DialogSDBReport):
        DialogSDBReport.setObjectName("DialogSDBReport")
        DialogSDBReport.resize(450, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogSDBReport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(DialogSDBReport)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.reportEdit = QtWidgets.QPlainTextEdit(DialogSDBReport)
        self.reportEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportEdit.sizePolicy().hasHeightForWidth())
        self.reportEdit.setSizePolicy(sizePolicy)
        self.reportEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.reportEdit.setObjectName("reportEdit")
        self.verticalLayout.addWidget(self.reportEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSDBReport)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.label_5.setBuddy(self.reportEdit)

        self.retranslateUi(DialogSDBReport)
        self.buttonBox.accepted.connect(DialogSDBReport.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSDBReport.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSDBReport)

    def retranslateUi(self, DialogSDBReport):
        _translate = QtCore.QCoreApplication.translate
        DialogSDBReport.setWindowTitle(_translate("DialogSDBReport", "Database information"))
        self.label_5.setText(_translate("DialogSDBReport", "Report:"))
